dist: focal
language: python
python:
  - "3.6"
branches:
  only:
    - master
    - develop
sudo: false
install:
- pip install pyyaml jsonschema pysha3
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-get install --only-upgrade libstdc++6

script:

# sanitation checks against testsets
- wget http://retestsil.ethdevops.io/retestsil
- chmod +x ./retestsil
- ./retestsil --version
- ./retestsil -t GeneralStateTests -- --checkhash --all --testpath $(pwd)
- ./retestsil -t BlockchainTests -- --checkhash --all --testpath $(pwd)
- ./retestsil -t BCGeneralStateTests -- --checkhash --all --testpath $(pwd)
- ./retestsil -t LegacyTests -- --checkhash --all --testpath $(pwd)
- ./retestsil -t TransactionTests -- --checkhash --all --testpath $(pwd)
- ./retestsil -t DifficultyTests -- --checkhash --all --testpath $(pwd)
- ./retestsil -t SIPTests -- --checkhash --all --testpath $(pwd)
- ./retestsil -t EOFTests -- --checkhash --all --testpath $(pwd)

# Retestsil does the format check upon test run and generation
#- make sani
